GAME:
  board_size: [3,3] 
  in_row: 3
MCTS:
  n_simulations: 25
  cpuct: 2.5
  dirichlet_alpha: 1.10
NN:
  n_res_layers: 5
AZ:
  eps: 50
  n_games: 20
  queue_len: 70
  temp:
    treshold: 10
    before: 1
    after: 1